name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Configurer Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installer les dépendances
      run: npm install -g pm2 && npm install --legacy-peer-deps

    - name: Démarrer l'application
      run: npm start
